---

- name: prerequesites
  hosts: localhost
  gather_facts: false

  vars:
    attendee_prefix: attendee_

  tasks:

  - name: include attendees
    include_vars:
      file: attendees.yml

  - name: send email
    mail:
      from: "Andreas Scherbaum <ads@wars-nicht.de>"
      to: "{{ item['name'] }}"
      charset: utf8
      subject: "CLT 2019 Ansible Workshop - Vorbereitungen"
      body: "{{lookup('file', 'prereq_mail.txt')}}"
    with_items: "{{ attendees }}"
